add new branch
Jasur7855/weather pull request #1
Opened 2024-12-22 09:42 UTC by Jasur7855

2025-01-02 13:28 UTC, antisedativ requested changes

2025-01-02 13:28 UTC, antisedative commented on package.json
>    }
для чего эта зависимость?

2025-01-02 13:28 UTC, antisedative commented on src/index.js
![image](https://github.com/user-attachments/assets/3c958345-bf2a-4c5c-a8a0-6a29caa45738)
при `npm run start` не подгружаются картинки элементов, при клике падает ошибка

2025-01-02 13:28 UTC, antisedative commented on src/index.js
![image](https://github.com/user-attachments/assets/d0b827b5-92b3-478a-a8dc-01f22bd3402c)

2025-01-02 13:28 UTC, antisedative commented on src/index.js
> +
все еще обработчик создается в цикле, нужно вынести и сделать универсальный обработчик, который будет обрабатывать элементы независимо от их количества

2025-01-02 13:28 UTC, antisedative commented on webpack.config.prod.js
> +});
в прод версии не должно быть devtool

2025-01-02 14:14 UTC, Jasur7855 commented on package.json
>    }
Удалил ее походу случайно установил

2025-01-02 14:15 UTC, Jasur7855 commented on src/index.js
Все исправил

2025-01-03 13:56 UTC, Jasur7855 commented on src/index.js
> +
Вынес его в отдельную функцию и повесил только один слушатель

2025-01-03 13:56 UTC, Jasur7855 commented on webpack.config.prod.js
> +});
Исправил

2025-01-05 15:39 UTC, merged